
import type { InventoryItem, Shelf, RequestItem } from '@/types';

export const placeholderInventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'Wireless Mouse XM300',
    sku: 'WM-XM300-BLK',
    category: 'Electronics',
    quantity: 120,
    location: 'Shelf A1-3',
    lastUpdated: '2023-10-25T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/mouse/200/200',
    description: 'Ergonomic wireless mouse with 5 programmable buttons and adjustable DPI.',
    tags: ['computer peripheral', 'office', 'ergonomic'],
    weight: 0.12, // kg
    dimensions: { length: 12, width: 7, height: 4 }, // cm
  },
  {
    id: '2',
    name: 'Mechanical Keyboard K780',
    sku: 'MK-K780-RGB',
    category: 'Electronics',
    quantity: 75,
    location: 'Shelf A1-4',
    lastUpdated: '2023-10-24T14:30:00Z',
    imageUrl: 'https://picsum.photos/seed/keyboard/200/200',
    description: 'Full-size mechanical keyboard with RGB backlighting and Cherry MX Brown switches.',
    tags: ['gaming', 'office', 'computer peripheral'],
    weight: 1.2,
    dimensions: { length: 45, width: 15, height: 3.5 },
  },
  {
    id: '3',
    name: 'Organic Green Tea (100 bags)',
    sku: 'OGT-100BG-ORG',
    category: 'Groceries',
    quantity: 300,
    location: 'Shelf C3-1',
    lastUpdated: '2023-10-26T08:15:00Z',
    imageUrl: 'https://picsum.photos/seed/tea/200/200',
    description: 'Certified organic green tea, rich in antioxidants. 100 tea bags.',
    tags: ['beverage', 'organic', 'healthy'],
    weight: 0.25,
    dimensions: { length: 15, width: 8, height: 7 },
  },
  {
    id: '4',
    name: 'Yoga Mat Premium Comfort',
    sku: 'YM-PC6MM-BLU',
    category: 'Sports & Outdoors',
    quantity: 50,
    location: 'Shelf B2-5',
    lastUpdated: '2023-10-22T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/yogamat/200/200',
    description: '6mm thick premium comfort yoga mat, non-slip, eco-friendly material.',
    tags: ['fitness', 'yoga', 'exercise'],
    weight: 1.5,
    dimensions: { length: 183, width: 61, height: 0.6 },
  },
  {
    id: '5',
    name: 'Hardcover Notebook Set (3 Pack)',
    sku: 'HN-S3PK-MIX',
    category: 'Office Supplies',
    quantity: 200,
    location: 'Shelf D1-2',
    lastUpdated: '2023-10-26T12:45:00Z',
    imageUrl: 'https://picsum.photos/seed/notebook/200/200',
    description: 'Set of 3 A5 hardcover notebooks, lined pages, assorted colors.',
    tags: ['stationery', 'writing', 'journal'],
    weight: 0.8,
    dimensions: { length: 21, width: 15, height: 4.5 }, // Stacked height for 3
  },
];

export const placeholderShelves: Shelf[] = [
  {
    id: 'shelf-001',
    name: 'Alpha-01-Top',
    locationDescription: 'Warehouse Section A, Row 1, Top Level',
    notes: 'Suitable for light to medium weight items. Max load 50kg.',
  },
  {
    id: 'shelf-002',
    name: 'Bravo-03-Mid',
    locationDescription: 'Warehouse Section B, Row 3, Middle Level',
    notes: 'Easy access shelf for frequently picked items.',
  },
  {
    id: 'shelf-003',
    name: 'Charlie-Receiving-Temp',
    locationDescription: 'Receiving Area, Temporary Holding Zone 2',
    notes: 'For newly received items awaiting sorting.',
  },
  {
    id: 'shelf-004',
    name: 'Delta-ColdStore-01',
    locationDescription: 'Cold Storage Unit 1, Shelf Rack 1',
    notes: 'Temperature controlled. For perishable goods.',
  }
];

export const placeholderRequests: RequestItem[] = [
  {
    id: 'REQ-001',
    itemName: 'Wireless Mouse XM300',
    itemId: '1',
    quantityRequested: 5,
    requesterName: 'Alice Johnson',
    requesterId: 'user-123',
    requestDate: '2023-11-01T10:00:00Z',
    status: 'Pending',
    notes: 'Urgent need for new marketing team members.',
  },
  {
    id: 'REQ-002',
    itemName: 'Mechanical Keyboard K780',
    itemId: '2',
    quantityRequested: 2,
    requesterName: 'Bob Williams',
    requesterId: 'user-456',
    requestDate: '2023-11-02T14:30:00Z',
    status: 'Approved',
    approvedBy: 'admin-001',
    approvalDate: '2023-11-03T09:15:00Z',
  },
  {
    id: 'REQ-003',
    itemName: 'Organic Green Tea (100 bags)',
    itemId: '3',
    quantityRequested: 10,
    requesterName: 'Carol Davis',
    requesterId: 'user-789',
    requestDate: '2023-11-03T11:20:00Z',
    status: 'Rejected',
    notes: 'Budget constraints for this quarter.',
  },
  {
    id: 'REQ-004',
    itemName: 'Hardcover Notebook Set (3 Pack)',
    itemId: '5',
    quantityRequested: 20,
    requesterName: 'David Brown',
    requesterId: 'user-101',
    requestDate: '2023-11-04T08:00:00Z',
    status: 'Approved', // Changed from Fulfilled
    approvedBy: 'admin-001',
    approvalDate: '2023-11-04T10:00:00Z',
  },
  {
    id: 'REQ-005',
    itemName: 'Yoga Mat Premium Comfort',
    itemId: '4',
    quantityRequested: 3,
    requesterName: 'Eve Wilson',
    requesterId: 'user-112',
    requestDate: '2023-11-05T16:45:00Z',
    status: 'Pending',
  },
];

